### ISSUE TITLE
"Fail Fast"

### ISSUE THREAD

**Issue by sbellware** [ntl/test-bench#1]
I think you might consider changing the "fail fast" language to something that is more descriptive of the feature than of a particular meme from agile.

E.g.: "abort on error", or something of the ilk.

As the field at large drifts away from the agile language and on to the next thing, the feature should be self-evident to anyone who wasn't around to know what RSpec (etc) was doing back in the day.

**Comment by ntl** [comment]
Fixed in version 0.9.5. It is now set to "abort on error."
