### ISSUE TITLE
Do not activate test bench automatically in CLI

### ISSUE THREAD

**Issue by ntl** [ntl/test-bench#10]
This effectively makes the CLI incompatible with any plugins. `require "test_bench/activate"` is then required somewhere in the tests.

**Comment by chrisnicola** [comment]
Make sense, so you could put this at the top of `test_helper` after loading any plugins. I'm still not sure how you would extend the CLI itself though if you wanted your plugin/extension to add a CLI flag, which I think would be potentially useful.

**Comment by ntl** [comment]
@chrisnicola I am not sure the CLI can be easily extensible without monkey patching it. I think it might need an overhaul to support such a feature. I'm also not sure that's the right approach; if running a single test is valuable, I think it ought to be supported by the CLI itself.

```
# bench some/test.rb:11 some/other/test:111
```

^^ That seems like a valuable addition to TestBench. However, it wasn't designed with that in mind, and may require significant overhauling to support.

**Comment by chrisnicola** [comment]
I agree, and the only real CLI extension I can come up with right now would be that. I made some more progress on my own with cleaner single test support so I'll submit a new pull request soon.
