### ISSUE TITLE
Disable context and test blocks with underscore

### ISSUE THREAD

**Issue by sbellware** [ntl/test-bench#23]
Would be nice if a `context` could be replaced with `_context`, and the block would not be executed. Same for `test` and `_test`.

Would provide a more friendly way to disable blocks without having to comment out code in an existing test file that is being debugged.

**Comment by ntl** [comment]
This was added to [TestBench 2.0](https://github.com/test-bench/test-bench).

**Comment by sbellware** [comment]
Awesome!!
