### ISSUE TITLE
Suggestion: Omit line with 'Test' when there's no test description

### ISSUE THREAD

**Issue by antoineLeclercq** [ntl/test-bench#24]
```ruby
test {}
```

Output:
```
Test
```

It would be nice if there was no output at all. Not even a blank line.

It seems unnecessary to force the test output to mimic the test implementation when the implementation is not using a test description.

Also, it appears that `context` already behaves this way.

**Comment by chrisnicola** [comment]
Can you describe the use case where you are creating test blocks with no descriptions? I'm just curious how this is used?

**Comment by ntl** [comment]
This was added to [TestBench 2](https://github.com/test-bench/test-bench).
