### ISSUE TITLE
Assertion count if test pass

### ISSUE THREAD

**Issue by destructobeam** [ntl/test-bench#25]
Not sure if this is an intentional design decision, but would it be possible to give stats on how many assertions are run per test?

My use case is testing API data contracts, and kind of makes sense to test all validation errors, all coercion errors, and all successes in one test each, rather than one test for each field.

Cheers.

**Comment by ntl** [comment]
What is the benefit to grouping the assertions within the same block?

Bear in mind that test-bench runs test files in a single pass, so you can run many individual tests off the same actuation. Given the following example, `some_http_api.()` would only get called once:

```ruby
context "Some HTTP API" do
  result = some_http_api.()

  test "Some test" do
    assert(...)
  end

  test "Other test" do
    assert(...)
  end
end
```

**Comment by destructobeam** [comment]
Ah okay, that makes total sense, thanks!

**Comment by ntl** [comment]
:+1:  Glad I could help!
