### ISSUE TITLE
[Proposal] Allow a user provided initializer to be loaded on `TestBench.activate`

### ISSUE THREAD

**Issue by chrisnicola** [ntl/test-bench#9]
In order to provide a convenient way for extensions to work or for users to customize TestBench's behaviour locally, it would be helpful to automatically load an initializer if available in the path.

I'm proposing this as an alternative to the changes in #8 so that those changes can exist as a separate extension module. However there is currently no obvious way to extend TestBench at activations.

I think an initializer is probably the most straightforward way to accomplish this. Extension module could then simply be required in that initializer if a user wishes to active that extensions behaviour.

I'm opening this for discussion but I will happily submit a pull request as well.

**Comment by ntl** [comment]
What about just loading test bench, then the plugin, then activating test bench? For instance, in a test helper, `test/test_helper.rb`

```ruby
require 'my/library'

require 'test_bench'
require 'test_bench/some_plugin'
TestBench.activate
```

**Comment by chrisnicola** [comment]
I considered that, however `cli.rb` already activates it. Also if the purpose of the plugin is to add a CLI option like parsing line numbers it needs to load during the bootstrapping of the CLI.

**Comment by ntl** [comment]
I think this is a valid reason to cause the executable to not activate by default (or at least activate it only if `--activate` is specified).

Re. extending the CLI, the CLI wasn't designed with extension in mind. And there is some awkwardness around the ruby environment, too. For instance, in order to detect plugins, I'd have to sift through the `$LOAD_PATH` to find specially named files the way minitest does.

On a side note, the feature you originally put forth as a PR seems like a reasonable feature to add to test bench proper, providing the implementation fits certain usability criteria.

**Comment by chrisnicola** [comment]
Yeah I definitely don't like the detecting and autoloading of plugins in the way minitest does. 

I'm suggesting a single standard init file that can be provided and assumed to existing in the execution path or passed as CLI variable. The init file can then be used to load any plugins/extensions explicitly. An alternative might be a YAML config file that could specify additional "requires" (among other options) but I felt an Ruby based init file was a more more flexible.

**Comment by chrisnicola** [comment]
As an example most Rack web servers do this, i.e., `/config/puma.rb`

**Comment by ntl** [comment]
The principal problem I have with standard init files is that they arise as the result of losing control of the loading sequence of the library that uses them. The result is a sort of coupling -- if you use puma, you have to have a `config/puma.rb` file in your project. It's not the worst convention in the world, but it isn't necessary if your library offers the ability to at least granularly control the initialization process.

**Comment by ntl** [comment]
I have been making efforts to make it easier to add a configurable executable within your project. For instance, you could add a file, `bench.rb`, to your project:

```ruby
# Load your project
require_relative './lib/my/library`

require 'test_bench'
require 'test_bench/cli'

# Configure the directory where test scripts are discovered
ENV['TEST_BENCH_TESTS_DIR'] ||= 'test/bench'

TestBench::CLI.() or exit 1
```

If you add a similar CLI loader to your project, you can alter the CLI before invoking it. The above example does so in a trivial way; it varies the directory from which tests are discovered.

I think this enables the ability to activate custom initializers. I'm going to close this issue for now; feel free to reopen if this is insufficient. Thanks!
